esphome:
  name: sala_janelas
  platform: ESP32
  board: esp32doit-devkit-v1
          
captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.25.205
    gateway: 192.168.25.1
    subnet: 255.255.255.0

  ap:
    ssid: Sala-Janelas
    password: !secret ap_password

i2c:
  sda: 21
  scl: 22

api:

logger:

ota:
    
sensor:

  - platform: bh1750
    name: "Sala - Sensor de Luminosidade 2"
    address: 0x23
    update_interval: 5s

  - platform: hdc1080
    temperature:
      name: "Sala - Sensor de Temperatura 2"
      filters:
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
    humidity:
      name: "Sala - Sensor de Umidade 2"
      filters:
        - median:
            window_size: 7
            send_every: 4
            send_first_at: 3
    update_interval: 5s

binary_sensor:

  - platform: gpio
    pin: GPIO18 
    name: "Sala - Sensor de Presenca - Jantar"
    device_class: motion
    filters:
      - delayed_off: 5s

  - platform: gpio
    pin: 
      number: GPIO04
      mode: INPUT_PULLUP
    name: "Sala - Janela 1"
    device_class: window

  - platform: gpio
    pin: 
      number: GPIO05
      mode: INPUT_PULLUP
    name: "Sala - Janela 2"
    device_class: window

